# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1281, 871))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setObjectName("gridLayout")
        self.city_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.city_label.setObjectName("city_label")
        self.gridLayout.addWidget(self.city_label, 0, 0, 1, 1)
        self.date_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 1, 0, 1, 1)
        self.apply_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.apply_button.setObjectName("apply_button")
        self.gridLayout.addWidget(self.apply_button, 1, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.temperature_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.temperature_checkbox.setChecked(True)
        self.temperature_checkbox.setObjectName("temperature_checkbox")
        self.gridLayout_2.addWidget(self.temperature_checkbox, 0, 0, 1, 1)
        self.clouds_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.clouds_checkbox.setChecked(True)
        self.clouds_checkbox.setObjectName("clouds_checkbox")
        self.gridLayout_2.addWidget(self.clouds_checkbox, 1, 0, 1, 1)
        self.pressure_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.pressure_checkbox.setChecked(True)
        self.pressure_checkbox.setObjectName("pressure_checkbox")
        self.gridLayout_2.addWidget(self.pressure_checkbox, 0, 1, 1, 1)
        self.precipitation_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.precipitation_checkbox.setChecked(True)
        self.precipitation_checkbox.setObjectName("precipitation_checkbox")
        self.gridLayout_2.addWidget(self.precipitation_checkbox, 1, 1, 1, 1)
        self.wind_checkbox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.wind_checkbox.setChecked(True)
        self.wind_checkbox.setObjectName("wind_checkbox")
        self.gridLayout_2.addWidget(self.wind_checkbox, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.widget_3d = QtWidgets.QWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3d.sizePolicy().hasHeightForWidth())
        self.widget_3d.setSizePolicy(sizePolicy)
        self.widget_3d.setMinimumSize(QtCore.QSize(620, 713))
        self.widget_3d.setObjectName("widget_3d")
        self.verticalLayout.addWidget(self.widget_3d)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 1, 2)
        self.widget_2d = QtWidgets.QWidget(self.gridLayoutWidget)
        self.widget_2d.setObjectName("widget_2d")
        self.gridLayout.addWidget(self.widget_2d, 2, 0, 1, 2)
        self.city_combo_box = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.city_combo_box.setObjectName("city_combo_box")
        self.gridLayout.addWidget(self.city_combo_box, 0, 1, 1, 1)
        self.date_combo_box = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.date_combo_box.setObjectName("date_combo_box")
        self.gridLayout.addWidget(self.date_combo_box, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Forecast Visualization"))
        self.city_label.setText(_translate("MainWindow", "Select city:"))
        self.date_label.setText(_translate("MainWindow", "Select date:"))
        self.apply_button.setText(_translate("MainWindow", "Apply"))
        self.temperature_checkbox.setText(_translate("MainWindow", "Temperature"))
        self.clouds_checkbox.setText(_translate("MainWindow", "Clouds"))
        self.pressure_checkbox.setText(_translate("MainWindow", "Pressure"))
        self.precipitation_checkbox.setText(_translate("MainWindow", "Precipitation"))
        self.wind_checkbox.setText(_translate("MainWindow", "Wind"))

