# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_expanding.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 860)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.city_label = QtWidgets.QLabel(self.centralwidget)
        self.city_label.setAlignment(QtCore.Qt.AlignCenter)
        self.city_label.setObjectName("city_label")
        self.gridLayout.addWidget(self.city_label, 0, 0, 1, 1)
        self.city_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.city_combo_box.setObjectName("city_combo_box")
        self.gridLayout.addWidget(self.city_combo_box, 0, 1, 1, 1)
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 0, 2, 1, 1)
        self.date_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.date_combo_box.setObjectName("date_combo_box")
        self.gridLayout.addWidget(self.date_combo_box, 0, 3, 1, 1)
        self.widget_2d = QtWidgets.QWidget(self.centralwidget)
        self.widget_2d.setMinimumSize(QtCore.QSize(621, 811))
        self.widget_2d.setObjectName("widget_2d")
        self.gridLayout.addWidget(self.widget_2d, 1, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.temperature_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.temperature_checkbox.setFont(font)
        self.temperature_checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.temperature_checkbox.setChecked(True)
        self.temperature_checkbox.setObjectName("temperature_checkbox")
        self.gridLayout_3.addWidget(self.temperature_checkbox, 0, 0, 1, 1)
        self.clouds_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.clouds_checkbox.setChecked(True)
        self.clouds_checkbox.setObjectName("clouds_checkbox")
        self.gridLayout_3.addWidget(self.clouds_checkbox, 1, 0, 1, 1)
        self.pressure_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.pressure_checkbox.setChecked(True)
        self.pressure_checkbox.setObjectName("pressure_checkbox")
        self.gridLayout_3.addWidget(self.pressure_checkbox, 0, 1, 1, 1)
        self.precipitation_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.precipitation_checkbox.setChecked(True)
        self.precipitation_checkbox.setObjectName("precipitation_checkbox")
        self.gridLayout_3.addWidget(self.precipitation_checkbox, 1, 1, 1, 1)
        self.wind_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.wind_checkbox.setChecked(True)
        self.wind_checkbox.setObjectName("wind_checkbox")
        self.gridLayout_3.addWidget(self.wind_checkbox, 2, 0, 1, 1)
        self.reset_camera_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_camera_button.setObjectName("reset_camera_button")
        self.gridLayout_3.addWidget(self.reset_camera_button, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.widget_3d = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3d.sizePolicy().hasHeightForWidth())
        self.widget_3d.setSizePolicy(sizePolicy)
        self.widget_3d.setMinimumSize(QtCore.QSize(620, 736))
        self.widget_3d.setObjectName("widget_3d")
        self.verticalLayout_2.addWidget(self.widget_3d)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Forecast Visualization"))
        self.city_label.setText(_translate("MainWindow", "Select city:"))
        self.date_label.setText(_translate("MainWindow", "Select date:"))
        self.temperature_checkbox.setText(_translate("MainWindow", "&Temperature"))
        self.temperature_checkbox.setShortcut(_translate("MainWindow", "Alt+T"))
        self.clouds_checkbox.setText(_translate("MainWindow", "&Clouds"))
        self.clouds_checkbox.setShortcut(_translate("MainWindow", "Alt+C"))
        self.pressure_checkbox.setText(_translate("MainWindow", "&Pressure"))
        self.pressure_checkbox.setShortcut(_translate("MainWindow", "Alt+P"))
        self.precipitation_checkbox.setText(_translate("MainWindow", "P&recipitation"))
        self.precipitation_checkbox.setShortcut(_translate("MainWindow", "Alt+R"))
        self.wind_checkbox.setText(_translate("MainWindow", "&Wind"))
        self.wind_checkbox.setShortcut(_translate("MainWindow", "Alt+W"))
        self.reset_camera_button.setText(_translate("MainWindow", "Reset map position"))

